# Generated by Django 4.2.11 on 2024-05-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typegift', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('tarif', models.TextField()),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.typesgift')),
            ],
        ),
    ]
